services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    networks:
      - local-monitor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - ./gdata:/var/lib/grafana
      # - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      # - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # - ./dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    networks:
      - local-monitor

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-monitoring
    ports:
      - "9103:9100"
    restart: unless-stopped
    networks:
      - local-monitor

networks:
  local-monitor:
    driver: bridge