global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['node-exporter-app:9100']
  - job_name: 'node-db'
    static_configs:
      - targets: ['node-exporter-db:9100']
  - job_name: 'node-proxy'
    static_configs:
      - targets: ['node-exporter-proxy:9100']
  - job_name: 'node-monitoring'
    static_configs:
      - targets: ['node-exporter-monitoring:9100']
