services:
  proxy:
    image: nginx:latest
    container_name: yii2-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - local-proxy

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-proxy
    ports:
      - "9102:9100"
    restart: unless-stopped
    networks:
      - local-proxy

networks:
  local-proxy:
    driver: bridge